// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2H9bGKqOaxFyT8dhNTOCkSty2HJTQ7ZQ',
    appId: '1:357379174827:web:3cd450b71a10671da0e2ee',
    messagingSenderId: '357379174827',
    projectId: 'hanuven-29189',
    authDomain: 'hanuven-29189.firebaseapp.com',
    storageBucket: 'hanuven-29189.appspot.com',
    measurementId: 'G-BLMG16H9VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIOczukn5rxLNKc1dktTwi2K7ANerMRGU',
    appId: '1:357379174827:android:fdc36c68e2a3f801a0e2ee',
    messagingSenderId: '357379174827',
    projectId: 'hanuven-29189',
    storageBucket: 'hanuven-29189.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv5MgI9G1eycav0r-h9f4LMTiYOQ3Onko',
    appId: '1:357379174827:ios:ec484acdc0b479ffa0e2ee',
    messagingSenderId: '357379174827',
    projectId: 'hanuven-29189',
    storageBucket: 'hanuven-29189.appspot.com',
    androidClientId: '357379174827-dm0pd58rrlh4jpocbjlg61cfrd4mp9rp.apps.googleusercontent.com',
    iosClientId: '357379174827-c8pb5emmco0oar5qma555c7be5rmr1n8.apps.googleusercontent.com',
    iosBundleId: 'com.indusianassist.hanuven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv5MgI9G1eycav0r-h9f4LMTiYOQ3Onko',
    appId: '1:357379174827:ios:ec484acdc0b479ffa0e2ee',
    messagingSenderId: '357379174827',
    projectId: 'hanuven-29189',
    storageBucket: 'hanuven-29189.appspot.com',
    androidClientId: '357379174827-dm0pd58rrlh4jpocbjlg61cfrd4mp9rp.apps.googleusercontent.com',
    iosClientId: '357379174827-c8pb5emmco0oar5qma555c7be5rmr1n8.apps.googleusercontent.com',
    iosBundleId: 'com.indusianassist.hanuven',
  );
}
